(function () {
  'use strict';
  const D=DietData, $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), fmt=n=>n===null?'—':new Intl.NumberFormat('zh-CN',{maximumFractionDigits:1}).format(n);
  let storage;try{storage=window.localStorage;}catch{storage={getItem(){throw Error('storage unavailable');},length:0};}
  const store=new D.Store(storage);
  let screen='today', activeDate=D.today(), range=7, detailDate='', mode='library', editingFood=null, selectedFood=null, meal='breakfast', search='', recordEditor=null, toastTimer;
  const dateLabel=date=>new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'long',day:'numeric',weekday:'short'}).format(new Date(date+'T12:00:00+08:00'));
  const mealOptions=value=>Object.entries(D.MEALS).map(([k,v])=>`<option value="${k}" ${k===value?'selected':''}>${v}</option>`).join('');
  const heading=(title,back='today')=>`<div class="screen-title"><button class="icon-button" data-nav="${back}" aria-label="返回">←</button><h2 tabindex="-1">${esc(title)}</h2></div>`;
  document.querySelector('.head').innerHTML='<div><p class="eyebrow">DAILY FUEL</p><h1>每日蛋白打卡</h1></div><div class="head-actions"><button class="text-button" data-nav="settings">目标</button><button class="reset" id="reset" aria-label="重置今日打卡">↻</button></div>';
  const hero=document.querySelector('.hero-wrap'); hero.id='todayHero';
  document.querySelector('.hero-copy').innerHTML='<div class="date"><i class="dot"></i><span id="date"></span></div><p class="label">今日蛋白质</p><p class="protein"><span id="protein">0</span><small> / <span id="proteinTarget">110</span> g</small></p><div class="bar" role="progressbar" aria-label="今日蛋白质进度" id="proteinBar"><i></i></div><p class="goal-copy" id="goal"></p>';
  document.querySelector('.ring').remove();
  hero.insertAdjacentHTML('beforeend','<div class="calorie-card"><div class="calorie-title"><h2>今日热量</h2><div><strong id="calories">0</strong><small> / <span id="calorieTarget">1800</span> kcal</small></div></div><div class="bar" role="progressbar" aria-label="今日热量进度" id="calorieBar"><i></i></div><p id="remainingCalories"></p></div>');
  const section=document.querySelector('.section');section.id='todaySection';
  section.innerHTML='<div id="meals"></div><div class="bottom-actions"><button class="primary wide" data-action="add">＋ 添加食物</button><div class="toolbar"><button class="secondary" data-action="copy">复制昨天饮食</button><button class="secondary" data-nav="history">历史记录</button></div></div><details class="quick"><summary>原有食物快捷打卡</summary><p class="muted">沿用原清单；点按添加一份，可继续调整或删除。</p><label class="field">快捷打卡餐次<select id="quickMeal">'+mealOptions(meal)+'</select></label><div id="quickFoods" class="quick-buttons" style="margin-top:12px"></div></details><p class="status-line" id="saveStatus">记录自动保存在本机 · 每天按北京时间切换</p>';
  document.querySelector('.app').insertAdjacentHTML('beforeend','<section id="otherScreen" class="screen" hidden></section><div class="toast" id="toast" role="status" hidden></div>');
  document.querySelector('.head').insertAdjacentHTML('afterend','<div id="storageNotice" class="notice" role="status" hidden></div>');
  let pendingConfirmation=null;
  document.querySelector('.app').insertAdjacentHTML('beforeend','<dialog id="confirmDialog" aria-labelledby="confirmTitle"><h2 id="confirmTitle">确认操作</h2><p id="confirmMessage"></p><div class="toolbar"><button class="secondary" data-action="confirm-no">取消</button><button class="primary" data-action="confirm-yes">确认</button></div></dialog>');
  function ask(message,callback){pendingConfirmation=callback;$('confirmMessage').textContent=message;$('confirmDialog').showModal();}
  $('confirmDialog').addEventListener('cancel',()=>{pendingConfirmation=null;});
  function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
  function act(fn){try{fn();warnings();return true;}catch(e){toast(e.message||'操作未完成，请重试');warnings();return false;}}
  function warnings(){$('storageNotice').hidden=!store.warnings.length;$('storageNotice').textContent=store.warnings.join('；');if(store.warnings.length)$('storageNotice').insertAdjacentHTML('beforeend',' <button class="text-button" data-action="backup">导出备份</button>');}
  function progress(id,value,target){const el=$(id);const pct=Math.min(100,value/target*100);el.firstElementChild.style.width=pct+'%';el.setAttribute('aria-valuemin','0');el.setAttribute('aria-valuemax',String(target));el.setAttribute('aria-valuenow',String(Math.min(value,target)));el.setAttribute('aria-valuetext',fmt(value)+' / '+fmt(target));}
  function summary(){const d=store.current();$('date').textContent=dateLabel(d.date);$('protein').textContent=fmt(d.totalProtein);$('proteinTarget').textContent=fmt(d.proteinTarget);$('calories').textContent=fmt(d.totalCalories)+(d.caloriesIncomplete?'+':'');$('calorieTarget').textContent=fmt(d.calorieTarget);$('goal').textContent=d.totalProtein>=d.proteinTarget?'今日蛋白质已达标':`还差 ${fmt(d.proteinTarget-d.totalProtein)}g 蛋白质`;$('goal').classList.toggle('good',d.totalProtein>=d.proteinTarget);progress('proteinBar',d.totalProtein,d.proteinTarget);progress('calorieBar',d.totalCalories,d.calorieTarget||1800);$('remainingCalories').textContent=(d.totalCalories>d.calorieTarget?`超出 ${fmt(d.totalCalories-d.calorieTarget)} kcal`:`剩余 ${fmt(d.calorieTarget-d.totalCalories)} kcal`)+(d.caloriesIncomplete?' · 部分旧记录未记录热量，当前为已知合计':'');}
  function recordHTML(r,readonly=false){return `<article class="record" data-record="${esc(r.id)}"><div class="record-top"><div><h3>${esc(r.snapshotName)}</h3><p>${fmt(r.protein)}g 蛋白质 · ${r.calories===null?'热量未记录':fmt(r.calories)+' kcal'+(r.caloriesEstimated?'（估算）':'')}</p>${r.snapshotNote?`<p>${esc(r.snapshotNote)}</p>`:''}</div>${readonly?`<span class="muted">${fmt(r.amount)} ${esc(r.snapshotUnit)}</span>`:`<div class="record-actions"><button class="amount-button" data-amount="${esc(r.id)}" aria-label="修改${esc(r.snapshotName)}份量">${fmt(r.amount)} ${esc(r.snapshotUnit)}</button><button class="icon-button" data-remove="${esc(r.id)}" aria-label="删除${esc(r.snapshotName)}记录">×</button></div>`}</div>${!readonly&&recordEditor===r.id?`<form class="inline-editor" data-record-form="${esc(r.id)}"><label>份量（${esc(r.snapshotUnit)}）<input name="amount" aria-label="食用份量" inputmode="decimal" type="number" min="0.01" max="1000000" step="any" value="${r.amount}" required data-live-amount="${esc(r.id)}"></label><button class="secondary" type="submit">完成</button></form>`:''}</article>`;}
  function mealsHTML(d,readonly=false){return Object.entries(D.MEALS).map(([k,label])=>{const list=d.foods.filter(r=>r.mealType===k);return `<section class="meal"><div class="meal-title"><h2>${label}</h2><small>${list.length?fmt(list.reduce((s,r)=>s+r.protein,0))+'g 蛋白质':''}</small></div>${list.length?list.map(r=>recordHTML(r,readonly)).join(''):`<p class="empty">${readonly?'未记录':'还没记录，吃完再记也可以。'}</p>`}</section>`;}).join('');}
  function renderToday(){summary();$('meals').innerHTML=mealsHTML(store.current());$('quickFoods').innerHTML=store.state.foods.filter(f=>f.builtin).map(f=>{const n=store.current().foods.filter(r=>r.foodId===f.id).reduce((s,r)=>s+r.amount,0);return `<button data-quick="${esc(f.id)}" class="${n?'selected':''}">${esc(f.name)} ＋${fmt(f.baseAmount)}${esc(f.unit)}${n?`<br><small>已记 ${fmt(n)}${esc(f.unit)}</small>`:''}</button>`;}).join('');}
  function navigate(next){checkDate();screen=next;recordEditor=null;if(next==='add'){mode='library';selectedFood=null;editingFood=null;search='';}render();window.scrollTo(0,0);$('otherScreen').querySelector('h2')?.focus();}
  function render(){warnings();const home=screen==='today';hero.hidden=!home;section.hidden=!home;$('otherScreen').hidden=home;$('reset').hidden=!home;if(home)renderToday();else if(screen==='add')renderAdd();else if(screen==='history')renderHistory();else if(screen==='detail')renderDetail();else if(screen==='settings')renderSettings();}
  function foodForm(f){const type=f?.type||'portion';return `<form id="foodForm" class="panel"><div class="form-grid"><label class="span2">食物名称<input name="name" maxlength="60" required value="${esc(f?.name)}" placeholder="例如：鸡胸肉"></label><label class="span2">记录方式<select name="type" id="foodType"><option value="portion" ${type==='portion'?'selected':''}>按份记录（个 / 瓶 / 片等）</option><option value="weight" ${type==='weight'?'selected':''}>按重量记录（克）</option></select></label><label>基准数量<input name="baseAmount" type="number" inputmode="decimal" min="0.01" max="1000000" step="any" value="${f?.baseAmount||1}" required></label><label>记录单位<input name="unit" maxlength="12" required value="${esc(f?.unit||'份')}" ${type==='weight'?'readonly':''}></label><p class="muted span2" id="basisHint">以下营养值对应上述基准数量。按重量建议填写每 100g。</p><label>蛋白质（g）<input name="protein" type="number" inputmode="decimal" min="0" max="1000000" step="any" value="${f?.protein??''}" required></label><label>热量（kcal）<input name="calories" type="number" inputmode="decimal" min="0" max="1000000" step="any" value="${f?.calories??''}" required></label><label class="span2">份量说明（选填）<input name="note" maxlength="100" value="${esc(f?.note)}" placeholder="例如：1 包 = 50g"></label></div>${f?.caloriesEstimated?'<p class="muted">当前热量为默认估算值，可按包装营养表修正。</p>':''}<p class="form-error" id="foodError" role="status"></p><div class="form-actions"><button type="submit" class="primary">${f?'保存修改':'保存并选择份量'}</button><button class="secondary" type="button" data-action="library">返回食物库</button></div>${f?`<button type="button" class="text-button wide backup" data-delete-food="${esc(f.id)}">删除食物库中的食物</button><p class="muted">修改和删除仅影响食物库，已有饮食记录保留当时快照。</p>`:''}</form>`;}
  function renderAdd(){const edit=editingFood&&store.state.foods.find(f=>f.id===editingFood);$('otherScreen').innerHTML=heading(edit?'编辑食物':'添加食物')+(!edit?`<div class="tabs"><button class="tab-button" data-action="library" aria-pressed="${mode==='library'}">从食物库选择</button><button class="tab-button" data-action="new-food" aria-pressed="${mode==='new'}">新建食物</button></div>`:'')+(mode==='new'||edit?foodForm(edit):`<label class="field">搜索食物<input id="foodSearch" type="search" placeholder="搜索名称" value="${esc(search)}"></label><div id="portionPanel"></div><p class="muted">收藏优先，其次按最近使用排序。点击食物设置份量。</p><div id="foodList" class="food-list"></div>`);if(mode==='library'&&!edit){renderFoodList();if(selectedFood)renderPortion();}}
  function renderFoodList(){const foods=store.sortedFoods().filter(f=>f.name.toLowerCase().includes(search.toLowerCase()));$('foodList').innerHTML=foods.length?foods.map(f=>`<article class="library-food"><button class="choose-food" data-select-food="${esc(f.id)}"><strong>${esc(f.icon||'🍽️')} ${esc(f.name)}</strong><small>${fmt(f.baseAmount)} ${esc(f.unit)} · ${fmt(f.protein)}g 蛋白质 · ${fmt(f.calories)} kcal${f.caloriesEstimated?'（估算）':''}${f.lastUsedAt?' · 最近用过':''}</small></button><button class="icon-button ${f.favorite?'favorite':''}" data-favorite="${esc(f.id)}" aria-label="${f.favorite?'取消收藏':'收藏'}${esc(f.name)}" aria-pressed="${f.favorite}">${f.favorite?'★':'☆'}</button><button class="icon-button" data-edit-food="${esc(f.id)}" aria-label="编辑${esc(f.name)}">✎</button></article>`).join(''):'<p class="empty">没有匹配的食物，可以新建一项。</p>';}
  function renderPortion(){const f=store.state.foods.find(f=>f.id===selectedFood);if(!f){selectedFood=null;$('portionPanel').innerHTML='';return;}$('portionPanel').innerHTML=`<form id="portionForm" class="panel"><h3>${esc(f.name)}</h3><p class="muted">${fmt(f.baseAmount)}${esc(f.unit)} = ${fmt(f.protein)}g 蛋白质 / ${fmt(f.calories)} kcal${f.note?' · '+esc(f.note):''}</p><div class="form-grid"><label>本次份量（${esc(f.unit)}）<input id="portionAmount" name="amount" type="number" inputmode="decimal" min="0.01" max="1000000" step="any" value="${f.baseAmount}" required></label><label>餐次<select name="mealType">${mealOptions(meal)}</select></label></div><div id="portionPreview" class="preview" aria-live="polite"></div><button type="submit" class="primary wide">加入今天</button></form>`;preview();$('portionPanel').scrollIntoView({block:'nearest'});}
  function preview(){const f=store.state.foods.find(f=>f.id===selectedFood);const amount=Number($('portionAmount')?.value);$('portionPreview').textContent=f&&Number.isFinite(amount)&&amount>0?`${fmt(f.protein*amount/f.baseAmount)}g 蛋白质 · ${fmt(f.calories*amount/f.baseAmount)} kcal`:'请输入大于 0 的份量';}
  function renderSettings(){const s=store.state.settings;$('otherScreen').innerHTML=heading('每日目标')+`<form id="targetForm" class="panel"><div class="form-grid"><label class="span2">蛋白质目标（g / 天）<input name="proteinTarget" type="number" inputmode="decimal" min="0.01" max="1000000" step="any" value="${s.proteinTarget}" required></label><label class="span2">热量目标（kcal / 天）<input name="calorieTarget" type="number" inputmode="decimal" min="0.01" max="1000000" step="any" value="${s.calorieTarget}" required></label></div><p class="muted">应用于今天和之后的记录。过去日期保留当时目标。</p><button class="primary wide" type="submit">保存目标</button></form><div class="panel"><h3>本机记录</h3><p class="muted">记录仅保存在当前浏览器，手机与电脑各自保存。可导出备份留存。</p><button class="secondary wide" data-action="backup">导出数据备份</button></div>`;}
  function renderHistory(){const stats=[store.stats(7),store.stats(30)];$('otherScreen').innerHTML=heading('历史记录')+`<div class="stat-grid">${stats.map((s,i)=>`<div class="stat-card"><h3>最近 ${i?30:7} 天平均</h3><strong>${fmt(s.protein)} <small style="display:inline">g 蛋白质</small></strong><p>${fmt(s.calories)} kcal</p><small>蛋白质：${s.recorded} 天记录<br>热量：${s.calorieDays} 天完整记录</small></div>`).join('')}</div><p class="muted">包含今天，按有记录的日期计算平均；未记录日期不按零计入。缺失热量的日期不参与热量平均。</p><div class="tabs"><button class="tab-button" data-range="7" aria-pressed="${range===7}">最近 7 天</button><button class="tab-button" data-range="30" aria-pressed="${range===30}">最近 30 天</button></div><div class="history-list">${store.stats(range).dates.map(date=>{const d=store.state.days[date];return `<button class="history-day" data-date="${date}" ${!d?'disabled':''}><div><strong>${date.slice(5).replace('-','月')}日${date===activeDate?' · 今天':''}</strong><small>${d?(d.totalProtein>=d.proteinTarget?'✓ 蛋白质已达标':'蛋白质未达标'):'未记录'}</small></div><div class="day-nutrition">${d?`${fmt(d.totalProtein)} / ${fmt(d.proteinTarget)} g<br>${fmt(d.totalCalories)}${d.caloriesIncomplete?'+':''} kcal${d.caloriesIncomplete?'（部分未记录）':''}`:'—'}</div></button>`;}).join('')}</div>`;}
  function renderDetail(){const d=store.state.days[detailDate];$('otherScreen').innerHTML=heading(dateLabel(detailDate),'history')+(d?`<div class="panel"><div class="detail-total"><strong>${fmt(d.totalProtein)}</strong> / ${fmt(d.proteinTarget)} g 蛋白质<br>${fmt(d.totalCalories)}${d.caloriesIncomplete?'+':''} / ${fmt(d.calorieTarget)} kcal</div>${d.caloriesIncomplete?'<p class="muted">部分旧记录未记录热量，以上为已知热量合计。</p>':''}</div><p class="readonly-note">历史详情只读，展示记录时的名称、份量、营养和目标。${d.legacy?'旧版未区分餐次，迁移记录统一放入加餐；旧版蛋白质达标下限为 100g。':''}</p>`+mealsHTML(d,true):'<p class="empty">当天没有记录。</p>');}
  function checkDate(){const date=D.today();if(date===activeDate)return false;activeDate=date;pendingConfirmation=null;$('confirmDialog').close();store.load();recordEditor=null;screen='today';selectedFood=null;render();toast('新的一天，昨天的记录已保留');return true;}
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const previousDate=activeDate;if(checkDate())return;
    if(b.dataset.nav){navigate(b.dataset.nav);return;}
    act(()=>{
      if(b.dataset.action==='confirm-no'){pendingConfirmation=null;$('confirmDialog').close();}
      else if(b.dataset.action==='confirm-yes'){const callback=pendingConfirmation;pendingConfirmation=null;$('confirmDialog').close();callback?.();}
      else if(b.id==='reset'){ask('重置今天的全部饮食记录？过去日期不会改变。',()=>{store.reset(previousDate);recordEditor=null;renderToday();toast('今天的记录已重置');});}
      else if(b.dataset.action==='add')navigate('add');
      else if(b.dataset.action==='copy'){const d=store.current(),y=store.state.days[D.offset(activeDate,-1)];if(d.copiedFrom===D.offset(activeDate,-1))throw Error('今天已经复制过昨天的饮食，无需重复复制');if(!y?.foods.length)throw Error('昨天没有可复制的饮食记录');ask(`将昨天的 ${y.foods.length} 条记录追加到今天？今天已有 ${d.foods.length} 条，同一天只能复制一次。`,()=>{if(checkDate())return;const n=store.copyYesterday();renderToday();toast(`已复制 ${n} 条饮食记录，可继续调整`);});}
      else if(b.dataset.action==='library'){mode='library';editingFood=null;selectedFood=null;renderAdd();}
      else if(b.dataset.action==='new-food'){mode='new';editingFood=null;renderAdd();}
      else if(b.dataset.action==='backup'){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([store.backup()],{type:'application/json'}));a.href=url;a.download='饮食记录备份-'+activeDate+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
      else if(b.dataset.quick){const f=store.state.foods.find(f=>f.id===b.dataset.quick);meal=$('quickMeal').value;store.add(f.id,f.baseAmount,meal);renderToday();toast('已添加'+f.name);}
      else if(b.dataset.amount){recordEditor=recordEditor===b.dataset.amount?null:b.dataset.amount;renderToday();document.querySelector('[data-live-amount]')?.focus();}
      else if(b.dataset.remove){store.remove(b.dataset.remove,previousDate);renderToday();toast('已删除当天记录');}
      else if(b.dataset.selectFood){selectedFood=b.dataset.selectFood;renderPortion();}
      else if(b.dataset.favorite){store.favorite(b.dataset.favorite);renderFoodList();}
      else if(b.dataset.editFood){editingFood=b.dataset.editFood;renderAdd();}
      else if(b.dataset.deleteFood){ask('删除这项食物？已经生成的当天和历史记录都会保留。',()=>{store.removeFood(b.dataset.deleteFood);editingFood=null;mode='library';renderAdd();toast('已删除食物，已有记录不受影响');});}
      else if(b.dataset.range){range=Number(b.dataset.range);renderHistory();}
      else if(b.dataset.date){detailDate=b.dataset.date;navigate('detail');}
    });
  });
  document.addEventListener('input',e=>{if(e.target.id==='foodSearch'){search=e.target.value;renderFoodList();}else if(e.target.id==='portionAmount')preview();else if(e.target.dataset.liveAmount){if(checkDate())return;const input=e.target;if(!input.validity.valid)return;act(()=>{store.amount(input.dataset.liveAmount,input.value,activeDate);summary();const r=store.current().foods.find(r=>r.id===input.dataset.liveAmount);const card=input.closest('.record');card.querySelector('p').textContent=fmt(r.protein)+'g 蛋白质 · '+(r.calories===null?'热量未记录':fmt(r.calories)+' kcal');card.querySelector('.amount-button').textContent=fmt(r.amount)+' '+r.snapshotUnit;card.closest('.meal').querySelector('.meal-title small').textContent=fmt(store.current().foods.filter(x=>x.mealType===r.mealType).reduce((s,x)=>s+x.protein,0))+'g 蛋白质';});}});
  document.addEventListener('change',e=>{if(e.target.id==='foodType'){const form=$('foodForm'),weight=e.target.value==='weight';form.elements.unit.value=weight?'g':'份';form.elements.unit.readOnly=weight;form.elements.baseAmount.value=weight?100:1;}else if(e.target.id==='quickMeal')meal=e.target.value;});
  document.addEventListener('submit',e=>{e.preventDefault();if(checkDate())return;const form=e.target,values=Object.fromEntries(new FormData(form));if(form.id==='foodForm'){try{const id=store.saveFood(values,editingFood);if(editingFood){editingFood=null;mode='library';selectedFood=null;renderAdd();toast('已保存修改，已有记录保持原快照');}else{mode='library';selectedFood=id;renderAdd();toast('已保存到食物库');}}catch(err){$('foodError').textContent=err.message;}}else act(()=>{if(form.id==='portionForm'){meal=values.mealType;store.add(selectedFood,values.amount,meal);navigate('today');toast('已加入今天并保存');}else if(form.id==='targetForm'){store.targets(values.proteinTarget,values.calorieTarget);navigate('today');toast('目标已保存');}else if(form.dataset.recordForm){store.amount(form.dataset.recordForm,values.amount,activeDate);recordEditor=null;renderToday();}});});
  setInterval(checkDate,15000);window.addEventListener('focus',checkDate);document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkDate();});window.addEventListener('storage',e=>{if(e.key===D.KEY||e.key?.startsWith('protein-checkin:')){store.load();render();}});
  render();
})();
